### ISSUE TITLE
How to use the data?

### ISSUE THREAD

**Issue by zzilch** [jnnan/chairs#1]
I want to visualize the dataset as you showed in the teaser.  But I find there is little document.
How should I use the data to get an complete interaction instance like thoses in the teaser with minimum code?

**Comment by zzilch** [comment]
find it in `visualize.py`

**Comment by zzilch** [comment]
Only find 7 objects (59,60,64,68,75,81,157) with pose sequences. The paper says "We ensure the data diversity with 46 participants
and 81 objects." Where are the other data?

**Comment by jnnan** [comment]
Please download the latest version of AHOI_Data
