### ISSUE TITLE
data not corresponding

### ISSUE THREAD

**Issue by zyh4813** [jnnan/chairs#2]
I downloaded the dataset provided in the readme. The data in DATA_FOLDER/*.npy does not correspond to the picture in IMG_FOLDER.
For example, "img_name.npy" contains '0235/0/rgb_0235_0_0158.jpg', '0235/0/rgb_0235_0_0168.jpg', '0235/0/rgb_0235_0_0173.jpg', etc., but all these images do not exist in IMG_FOLDER. May I ask how the data in these npy files correspond to the pictures?
![image](https://user-images.githubusercontent.com/73029496/234199614-dc5166ef-8dd5-4645-8e4f-08fec92aeb2c.png)
![image](https://user-images.githubusercontent.com/73029496/234201023-1bb55e8d-8489-473f-ac2e-cc63fff0120e.png)

**Comment by jnnan** [comment]
0235/0/rgb_****.jpg should be found in rimage.zip. Some mismatch between image filenames and img_name.npy has been fixed in the latest version of AHOI_Data.

**Comment by zyh4813** [comment]
Thanks!
